### ISSUE TITLE
How to stop the map from re rendering while selecting different locations , but by keeping the location values as retrieved ?

### ISSUE THREAD

**Issue by jjthomas96** [imranhsayed/google-maps-in-react#1]
Hello Imran , 
First of all i want to clear this is not an issue  but i did a lot of research on this ,i am not getting any solutions so please look through and help me ,
Basically its like  when we select a location on the map by dragging the marker ,i don't want the map to  refresh and reset the values and also the pin is coming back to the center after re render takes place,
Is there any solution in "shouldcomponentupdate" ?? which doesn't allow you to re render the whole thing but by keep updating the values which were retrieved like address ,lat and long in input fields !!

And also i tried different things in shouldcomponentupdate method like by returning it as false , but over there map was not re rendering i could drag the pin from where i left off , i could see the locations getting updated in the console below , but values of those locations were not displaying in the input fields provided !
 
In simple words if i want to say , Whenever i drag and drop pin on location ,Location value must be retrieved continuous without the pin coming back to the center of the map, so that i can resume retrieving of location from where i left the marker pin on the map .
Please Help Me out !!

```
shouldComponentUpdate( nextProps, nextState ){
			if (this.state.markerPosition.lat !== this.props.center.lat ||
				this.state.address !== nextState.address ||
				this.state.city !== nextState.city ||
				this.state.area !== nextState.area ||
				this.state.state !== nextState.state
			) {
				return true
			} else if ( this.props.center.lat === nextProps.center.lat ){
				return false
			}
		return true
	}
```

**Comment by niko888f** [comment]
onMarkerDragEnd() 
// adding the following in this.setState
  markerPosition: {
            lat: newLat,
            lng: newLng,
          },
          mapPosition: {
            lat: newLat,
            lng: newLng,
          },
