### ISSUE TITLE
not able to search by typing full address on search bar, getting error for length of undefined using this code.

### ISSUE THREAD

**Issue by yogita3279** [imranhsayed/google-maps-in-react#15]
I used GooglePlacesAutocomplete, Link- https://www.npmjs.com/package/react-google-places-autocomplete and it worked

**Comment by iaminawe** [comment]
I am also getting length undefined error on automcomplete

**Comment by yogita3279** [comment]
Hi, try with GooglePlacesAutocomplete Link- https://www.npmjs.com/package/react-google-places-autocomplete instead of Autocomplete?

**Comment by yogita3279** [comment]
> I am also getting length undefined error on autocomplete- this issue should still be open
Try this https://www.npmjs.com/package/react-google-places-autocomplete

**Comment by yogita3279** [comment]
https://github.com/yogita3279/HeatMapTracker/blob/master/src/components/HeatMapWithGoogleMap.js

**Comment by iaminawe** [comment]
Thank you for responding. I did try that alternative autocomplete package and while it worked for me in that it returned lookup results - I was not able to get it to work correctly with the map and input fields

Can you please share what your code for the autocomplete part looks like

```
          <Autocomplete
              style={{
                width: '100%',
                height: '40px',
                paddingLeft: '16px',
                marginTop: '2px',
                marginBottom: '500px'
              }}
              onPlaceSelected={ this.onPlaceSelected }
              types={['(regions)']}
            />

```
Thanks for posting the example above - would this part be a direct replacement or would it still need some adjustment

 <GooglePlacesAutocomplete
            onSelect={({ description }) => (
                Geocode.fromAddress(description).then(
                response => {
                    const { lat, lng } = response.results[0].geometry.location;
                    const address=response.results[0].formatted_address
                    console.log(lat, lng, address);
                        this.setState( {
                        address: ( address ) ? description : '',
                        markerPosition: {
                            lat: lat,
                            lng: lng
                        },
                        mapPosition: {
                            lat: lat,
                            lng: lng
                        },
                        } )
                    },
                    error => {
                    console.error(error);
                    }
                )
            )}/>

**Comment by iaminawe** [comment]
That works as a direct replacement - Thank you so much - this can be closed again

**Comment by yogita3279** [comment]
:) No worries!
